# Generated by Django 4.2.4 on 2023-08-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_auto_20230702_0921"),
    ]

    operations = [
        migrations.RemoveField(model_name="userbase", name="country",),
        migrations.AlterField(
            model_name="userbase",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
