# Generated by Django 4.2.1 on 2023-05-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("-created",), "verbose_name_plural": "products"},
        ),
    ]
