# Generated by Django 4.1.6 on 2023-06-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(default="images/default.png", upload_to="images/"),
        ),
    ]
