# Generated by Django 4.2.1 on 2023-08-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_productspecification_producttype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Please add alternative text",
                max_length=255,
                null=True,
                verbose_name="Alternative Text",
            ),
        ),
    ]
